# The app can be reached at https://whoami.<FQDN>:8443
---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami-app
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami-app
  labels:
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/name: whoami
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/name: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whoami-app
  name: whoami
  labels:
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: whoami
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: whoami
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          imagePullPolicy: Always
          # Listen on port 8080 to run as non-root user
          args:
            - --port
            - '8080'
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            # Run the container as nobody:nogroup
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              memory: '50Mi'
              cpu: '500m' # 50%
          ports:
            - containerPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-websecure
  namespace: whoami-app
  labels:
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/name: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: host-selfsigned-cert # <<< Use 'host-imported-cert' if you want to use the SSL cert specified in the settings.
