---
# Plex Media Server does not support running behind a reverse proxy with
# subpath, e.g. https://omv7box.local:8443/plex.
# You can only access it via NodePort, e.g. http://omv7box.local:32400/web
#
# Uncomment the `IngressRoute` if you want to access Plex Media Server
# via https://omv7box.local:8443 for example.
---
apiVersion: v1
kind: Namespace
metadata:
  name: plex-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-dir
  namespace: plex-app
spec:
  storageClassName: shared-folder
  capacity:
    storage: 2Gi
  hostPath:
    path: <ABSOLUTE_SHARED_FOLDER_PATH> # <<< Replace
    type: Directory
  accessModes:
    - ReadWriteMany
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: config-dir
  namespace: plex-app
spec:
  storageClassName: shared-folder
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "2Gi"
  volumeName: config-dir
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: plex-media-server
  namespace: plex-app
spec:
  repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
  chart: plex-media-server
  targetNamespace: plex-app
  valuesContent: |-
    pms:
      configExistingClaim: config-dir
    ingress:
      enabled: false
    rclone:
      enabled: false
    service:
      type: NodePort
    extraEnv:
      # Specifies the UID for the process running in the container.
      PLEX_UID: "<UID>" # <<< Replace
      # Specifies the GID for the process running in the container.
      # Defaults to `users`.
      PLEX_GID: "100" # <<< Replace if needed
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: plex-media-server-websecure
#   namespace: plex-app
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: PathPrefix(`/`)
#       kind: Rule
#       services:
#         - name: plex-media-server
#           port: 32400
#   tls:
#     secretName: host-selfsigned-cert # <<< Use 'host-imported-cert' if you want to use the SSL cert specified in the settings.
