---
# Can't get it working to access MinIO console via subpath, e.g.
# https://omv7box.local:8443/minio, even when MINIO_BROWSER_REDIRECT_URL
# and MINIO_BROWSER_CONTENT_SECURITY_POLICY are set. Contributions to
# that issue are welcome.
#
# In the meanwhile you can only access it via NodePort, e.g.
# http://omv7box.local:30901
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  name: minio
  namespace: minio-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio
      app.kubernetes.io/name: minio
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: minio
        app.kubernetes.io/name: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          # Specifies the UID for the process running in the container.
          runAsUser: {{ uid('<NAME>') }} # <<< Replace
          # Specifies the GID for the process running in the container.
          # Defaults to `users`.
          runAsGroup: {{ gid('users') }} # <<< Replace if needed
        args:
        - "server"
        - "/data/"
        env:
        - name: "MINIO_ADDRESS"
          value: ":9000"
        - name: "MINIO_CONSOLE_ADDRESS"
          value: ":9001"
        - name: "MINIO_ROOT_USER"
          value: "admin"
        - name: "MINIO_ROOT_PASSWORD"
          value: "openmediavault"
#       - name: "MINIO_BROWSER_REDIRECT_URL"
#         value: "https://omv7box.local:8443/minio"
#       - name: "MINIO_BROWSER_CONTENT_SECURITY_POLICY"
#         value: "default-src 'self' 'unsafe-eval' 'unsafe-inline';"
        ports:
        - containerPort: 9000
          name: api
          protocol: TCP
        - containerPort: 9001
          name: console
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: "/data/"
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          type: Directory
          # Insert the name of the shared folder you want to use.
          # Make sure the configured UID/GID the container is running
          # with has access to that directory.
          path: {{ sharedfolder_path('<NAME>') }} # <<< Replace
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-app
spec:
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  type: NodePort
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30900
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30901
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: minio-console-websecure
#   namespace: minio-app
# spec:
#   entryPoints:
#   - websecure
#   routes:
#   - match: PathPrefix(`/minio`)
#     kind: Rule
#     services:
#     - name: minio
#       port: 30901
#   tls:
#     secretName: host-selfsigned-cert # <<< Use 'host-imported-cert' if you want to use the SSL cert specified in the settings.
