# The app can be reached at http://<FQDN>:8080/smokeping
# Change the following variables to adapt the recipe to your needs.
{% set emailPass = '<MODIFY>' %}
{% set emailUser = '<MODIFY>' %}
{% set emailHost = '<MODIFY>' %}
{% set configSharedFolderName = '<MODIFY>' %}
{% set dataSharedFolderName = '<MODIFY>' %}
# !!! Only modify the following manifest if you need to make custom changes. !!!
---
apiVersion: v1
kind: Namespace
metadata:
  name: smokeping-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping-ssmtp
  namespace: smokeping-app
data:
  ssmtp.conf: |
    root={{ emailUser }}
    mailhub={{ emailHost }}
    AuthUser={{ emailUser }}
    AuthPass={{ emailPass }}
    UseTLS=YES
    UseSTARTTLS=YES
    FromLineOverride=YES
    hostname=smokeping.kubernetes.default.svc
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: smokeping-web
  namespace: smokeping-app
  labels:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/name: smokeping
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/smokeping`)
      kind: Rule
      services:
        - name: smokeping
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smokeping
  namespace: smokeping-app
  labels:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/name: smokeping
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/name: smokeping
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  namespace: smokeping-app
  labels:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/name: smokeping
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: smokeping
      app.kubernetes.io/name: smokeping
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: smokeping
        app.kubernetes.io/name: smokeping
    spec:
      containers:
      - name: smokeping
        image: linuxserver/smokeping:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: "/config"
            name: config
          - mountPath: "/data"
            name: data
          - mountPath: "/etc/ssmtp/ssmtp.conf"
            name: ssmtp-config
            subPath: ssmtp.conf
            readOnly: true
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: {{ tz() }}
      volumes:
        - name: config
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(configSharedFolderName) }}
        - name: data
          hostPath:
            type: Directory
            # Insert the name of the shared folder you want to use.
            # Make sure the configured UID/GID the container is running
            # with has access to that directory.
            path: {{ sharedfolder_path(dataSharedFolderName) }}
        - name: ssmtp-config
          configMap:
            name: smokeping-ssmtp
