# The app can be reached at https://<FQDN>:8443/filebrowser
---
apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser-app
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: filebrowser
  namespace: filebrowser-app
spec:
  repo: https://utkuozdemir.org/helm-charts
  chart: filebrowser
  targetNamespace: filebrowser-app
  valuesContent: |-
    securityContext:
      runAsNonRoot: true
      runAsUser: <UID> # <<< Replace this with the UID of the user who has access to the shared folder.
      runAsGroup: 100 # This is the GID of the `users` group.
    rootDir:
      type: hostPath
      hostPath:
        path: <ABS_SHARED_FOLDER_PATH> # <<< Replace this with the absolute path of the shared folder you want to use.
    config:
      baseURL: /filebrowser
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-websecure
  namespace: filebrowser-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/filebrowser`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: host-selfsigned-cert # <<< Use 'host-imported-cert' if you want to use the SSL cert specified in the settings.
