# The app can be reached at https://<FQDN>:8443/filebrowser
---
apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser-app
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: filebrowser
  namespace: filebrowser-app
spec:
  repo: https://utkuozdemir.org/helm-charts
  chart: filebrowser
  targetNamespace: filebrowser-app
  valuesContent: |-
    securityContext:
      runAsNonRoot: true
      # Specifies the UID for the process running in the container.
      runAsUser: {{ uid('<NAME>') }} # <<< Replace
      # Specifies the GID for the process running in the container.
      # Defaults to `users`.
      runAsGroup: {{ gid('users') }} # <<< Replace if needed
    rootDir:
      type: hostPath
      hostPath:
      # Insert the name of the shared folder you want to use.
      # Make sure the configured UID/GID the container is running
      # with has access to that directory.
      path: {{ sharedfolder_path('<NAME>') }} # <<< Replace
    config:
      baseURL: /filebrowser
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-websecure
  namespace: filebrowser-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/filebrowser`)
      kind: Rule
      services:
        - name: filebrowser
          port: 80
  tls:
    secretName: host-selfsigned-cert # <<< Use 'host-imported-cert' if you want to use the SSL cert specified in the settings.
